vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    house:
      uri_prefix: /images/house
      upload_destination: "%kernel.project_dir%/public/images/house"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
    icones_images:
      uri_prefix: /images/icones
      upload_destination: "%kernel.project_dir%/public/images/icones"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
